version: '3.8'

services:
  message_server:
    image: message_server:1.0
    build:
      context: .
      dockerfile: MessageServer/dockerfile
    ports:
      - "20200:20200"

  post_service:
    image: post_service:1.0
    build:
      context: .
      dockerfile: PostService/dockerfile
    depends_on:
      - message_server

  db_service:
    image: db_service:1.0
    build:
      context: .
      dockerfile: DbHandler/dockerfile
    depends_on:
      - message_server

  account_service:
    image: account_service:1.0
    build:
      context: .
      dockerfile: AccountService/dockerfile
    depends_on:
      - message_server

  simulator_service:
    image: simulator_service:1.0
    build:
      context: .
      dockerfile: SimulatorApp/dockerfile
    depends_on:
      - account_service

networks:
  default:
    driver: bridge
