FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY AccountService/AccountService.csproj ./AccountService/
COPY DatabaseConnector/DatabaseConnector.csproj ./DatabaseConnector/
COPY RabbitMqDefault/RabbitMqDefault.csproj ./RabbitMqDefault/

RUN dotnet restore AccountService/AccountService.csproj

COPY . .

RUN dotnet publish AccountService/AccountService.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/runtime:8.0

WORKDIR /app

COPY --from=build /out .

ENTRYPOINT ["dotnet", "AccountService.dll"]