# Use the official .NET SDK image for building the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copy the BitToolbox project from the lib directory
COPY lib/Service/Service.csproj lib/Service/
COPY lib/. lib/

# Copy the MessageServer project files
COPY AccountService/AccountService.csproj AccountService/
COPY AccountService/. AccountService/

# Restore dependencies
RUN dotnet restore AccountService/AccountService.csproj

# Build the project
RUN dotnet publish AccountService/AccountService.csproj -c Release -o out

# Use a smaller runtime image for the final deployment
FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app

# Copy the compiled output from the build environment
COPY --from=build-env /app/out .

# Expose the application port
EXPOSE 20200

# Specify the entry point for the application
ENTRYPOINT ["dotnet", "AccountService.dll"]